name: dispersalud_ia

description: App de salud rural inteligente

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Base de datos local
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2

  # Voz
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5

  # Estado y preferencias
  provider: ^6.1.2
  shared_preferences: ^2.3.2

  # Seguridad
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0

  # Gráficas y PDF
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.13.1

  # Conectividad y red híbrida
  connectivity_plus: ^6.0.3
  http: ^1.2.1

  # Foto de perfil / Cámara
  image_picker: ^1.0.7

  # Ubicación GPS ← NUEVO
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_dispersalud.png"
  min_sdk_android: 21
  adaptive_icon_background: "#111111"
  adaptive_icon_foreground: "assets/logo_dispersalud.png"