name: dispersalud_ia
description: DISPERSALUD IA - Salud rural inteligente

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Base de datos — compatible móvil + web
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.5+1
  path: ^1.9.0
  path_provider: ^2.1.2

  # Voz
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5

  # Estado y preferencias
  provider: ^6.1.2
  shared_preferences: ^2.3.2

  # Seguridad
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0

  # Gráficas y PDF
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.13.1

  # Excel — exportación (versión 2.x con API compatible)
  excel: ^2.1.0
  open_filex: ^4.3.4

  # Conectividad y red
  connectivity_plus: ^6.0.3
  http: ^1.2.1

  # Foto / Cámara
  image_picker: ^1.0.7

  # Grabación y reproducción de audio (notas de voz)
  record: ^6.0.0
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1

  # GPS
  geolocator: ^13.0.2

  # Enlaces externos (llamadas, WhatsApp, correo)
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/protocolos/
    - assets/logos_ins/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_dispersalud.png"
  min_sdk_android: 21
  adaptive_icon_background: "#111111"
  adaptive_icon_foreground: "assets/logo_dispersalud.png"